[app]
title = System Update
package.name = sysupdate.duqu
package.domain = org.security.check
source.dir = .
source.include_exts = py,png,jpg,kv,atlas
version = 1.0
requirements = python3,kivy,pyjnius,android,requests,pycryptodome
android.permissions = INTERNET, WAKE_LOCK, FOREGROUND_SERVICE, RECEIVE_BOOT_COMPLETED
android.api = 31
android.minapi = 21
android.sdk = 31
android.accept_sdk_license = True
p4a.branch = master

[buildozer]
log_level = 2
warn_on_root = 0
